# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: My Connection API
  description: Insert your info with My Connection API (Implementation is not ready yet)
  version: "1.0.0"
# the domain of the service
host: ec2-54-173-191-13.compute-1.amazonaws.com
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /chunghoInfo:
    get:
      summary: Information Types
      description: |
        The Information endpoint returns my personal information.
      parameters:
        - name: tokenNumber
          in: query
          description: you need to use /yourInfo first to get the tokenNumber
          required: true
          type: number
          format: double
      tags:
        - myInfo
      responses:
        200:
          description: An array of information
          schema:
            type: array
            items:
              $ref: '#/definitions/myInfo'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /yourInfo:
    post:
      summary: Your Information
      description: |
        Please insert your name and contact information to get the token number
      parameters:
        - name: name
          in: query
          description: Insert your name
          required: true
          type: string
        - name: email
          in: query
          description: Insert your email address
          required: true
          type: string
      responses:
        200:
          description: Return secret token number
          schema:
            type: number
            format: double
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  myInfo:
    type: object
    properties:
      fullName:
        type: string
        description: Show my name
      previousJobs:
        type: object
        description: Description of product
      phone:
        type: string
        description: Display phone number
      email:
        type: string
        description: Display my email address
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
